-- KBS Onliners Supabase setup
-- Paste this into Supabase SQL Editor and run it once.

create table if not exists public.site_content (
  id text primary key,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  service text not null,
  message text not null,
  source text not null default 'website',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

insert into public.site_content (id, content)
values (
  'main',
  '{
    "businessName": "KBS Onliners",
    "tagline": "URA & URSB Service Desk",
    "whatsappNumber": "256779682856",
    "heroEyebrow": "Reliable online support in Uganda",
    "heroTitle": "KBS Onliners makes URA and URSB processes easier to complete.",
    "heroText": "Get guided help for tax registration, TIN support, business name searches, company registration steps, return filing preparation, document follow-up, and general online service inquiries.",
    "announcementEnabled": true,
    "announcementTitle": "Need urgent URA or URSB help?",
    "announcementText": "Send your service request through WhatsApp and KBS Onliners will guide you on the next preparation step.",
    "testimonials": [
      { "category": "ura", "quote": "KBS Onliners helped me understand what I needed before starting my TIN inquiry. The instructions were clear.", "name": "Sarah N.", "label": "URA support" },
      { "category": "ursb", "quote": "The business registration checklist saved time. I knew what details to prepare before asking for help.", "name": "Brian K.", "label": "URSB support" },
      { "category": "documents", "quote": "They reviewed my document requirements and explained the next steps without making the process complicated.", "name": "Agnes T.", "label": "Document readiness" },
      { "category": "ura", "quote": "Fast WhatsApp response and patient guidance. I appreciated the reminders about keeping passwords private.", "name": "Daniel M.", "label": "URA portal inquiry" }
    ],
    "faqs": [
      { "question": "Is KBS Onliners part of URA or URSB?", "answer": "No. KBS Onliners is an independent support service that helps clients understand and prepare for official URA and URSB online processes." },
      { "question": "Should I share my password?", "answer": "No. Do not share official portal passwords, mobile money PINs, bank PINs, or one-time passwords. KBS Onliners can guide you without receiving private credentials." },
      { "question": "How do I start?", "answer": "Use the contact form or WhatsApp button. Describe the service, your current stage, and any non-sensitive reference information available." },
      { "question": "Are government fees included?", "answer": "Government fees, where applicable, are separate from service assistance fees. Confirm all official payment details before making payment." },
      { "question": "Can I get same-day help?", "answer": "Many inquiries can start the same day through WhatsApp. Completion times depend on the service type, client readiness, and official system availability." }
    ]
  }'::jsonb
)
on conflict (id) do nothing;

alter table public.site_content enable row level security;
alter table public.inquiries enable row level security;

-- Everyone can read approved public site content.
drop policy if exists "Public can read site content" on public.site_content;
create policy "Public can read site content"
on public.site_content
for select
to anon, authenticated
using (true);

-- Only signed-in Supabase users can update site content from admin.html.
drop policy if exists "Authenticated users can manage site content" on public.site_content;
create policy "Authenticated users can manage site content"
on public.site_content
for all
to authenticated
using (true)
with check (true);

-- Website visitors can submit inquiries.
drop policy if exists "Anyone can submit inquiries" on public.inquiries;
create policy "Anyone can submit inquiries"
on public.inquiries
for insert
to anon, authenticated
with check (true);

-- Signed-in Supabase users can view and manage inquiries in the Supabase dashboard.
drop policy if exists "Authenticated users can manage inquiries" on public.inquiries;
create policy "Authenticated users can manage inquiries"
on public.inquiries
for all
to authenticated
using (true)
with check (true);